import type { Layout } from "./types";

export const kedmanee: Layout = {
  id: "kedmanee",
  name: "Kedmanee",
  keys: {
    KeyQ: { normal: "ๆ", shift: "๐", finger: "left-pinky", row: "top" },
    KeyW: { normal: "ไ", shift: "\"", finger: "left-ring", row: "top" },
    KeyE: { normal: "ำ", shift: "ฎ", finger: "left-middle", row: "top" },
    KeyR: { normal: "พ", shift: "ฑ", finger: "left-index", row: "top" },
    KeyT: { normal: "ะ", shift: "ธ", finger: "left-index", row: "top" },
    KeyY: { normal: "ั", shift: "ํ", finger: "right-index", row: "top" },
    KeyU: { normal: "ี", shift: "๊", finger: "right-index", row: "top" },
    KeyI: { normal: "ร", shift: "ณ", finger: "right-middle", row: "top" },
    KeyO: { normal: "น", shift: "ฯ", finger: "right-ring", row: "top" },
    KeyP: { normal: "ย", shift: "ญ", finger: "right-pinky", row: "top" },
    KeyA: { normal: "ฟ", shift: "ฤ", finger: "left-pinky", row: "home" },
    KeyS: { normal: "ห", shift: "ฆ", finger: "left-ring", row: "home" },
    KeyD: { normal: "ก", shift: "ฏ", finger: "left-middle", row: "home" },
    KeyF: { normal: "ด", shift: "โ", finger: "left-index", row: "home" },
    KeyG: { normal: "เ", shift: "ฌ", finger: "left-index", row: "home" },
    KeyH: { normal: "้", shift: "็", finger: "right-index", row: "home" },
    KeyJ: { normal: "่", shift: "๋", finger: "right-index", row: "home" },
    KeyK: { normal: "า", shift: "ษ", finger: "right-middle", row: "home" },
    KeyL: { normal: "ส", shift: "ศ", finger: "right-ring", row: "home" },
    KeyZ: { normal: "ผ", shift: "(", finger: "left-pinky", row: "bottom" },
    KeyX: { normal: "ป", shift: ")", finger: "left-ring", row: "bottom" },
    KeyC: { normal: "แ", shift: "ฉ", finger: "left-middle", row: "bottom" },
    KeyV: { normal: "อ", shift: "ฮ", finger: "left-index", row: "bottom" },
    KeyB: { normal: "ิ", shift: "ฺ", finger: "left-index", row: "bottom" },
    KeyN: { normal: "ื", shift: "์", finger: "right-index", row: "bottom" },
    KeyM: { normal: "ท", shift: "?", finger: "right-index", row: "bottom" },
    Space: { normal: " ", shift: " ", finger: "right-index", row: "bottom" },
  },
};
